// Code generated by protoc-gen-go. DO NOT EDIT.
// source: combat.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CombatGetInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CombatGetInfoReq) Reset()         { *m = CombatGetInfoReq{} }
func (m *CombatGetInfoReq) String() string { return proto.CompactTextString(m) }
func (*CombatGetInfoReq) ProtoMessage()    {}
func (*CombatGetInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{0}
}

func (m *CombatGetInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatGetInfoReq.Unmarshal(m, b)
}
func (m *CombatGetInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatGetInfoReq.Marshal(b, m, deterministic)
}
func (m *CombatGetInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatGetInfoReq.Merge(m, src)
}
func (m *CombatGetInfoReq) XXX_Size() int {
	return xxx_messageInfo_CombatGetInfoReq.Size(m)
}
func (m *CombatGetInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatGetInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_CombatGetInfoReq proto.InternalMessageInfo

type CombatGetInfoResp struct {
	Code                 int32         `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	PlayerInitList       []*PlayerInit `protobuf:"bytes,2,rep,name=PlayerInitList,proto3" json:"PlayerInitList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CombatGetInfoResp) Reset()         { *m = CombatGetInfoResp{} }
func (m *CombatGetInfoResp) String() string { return proto.CompactTextString(m) }
func (*CombatGetInfoResp) ProtoMessage()    {}
func (*CombatGetInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{1}
}

func (m *CombatGetInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatGetInfoResp.Unmarshal(m, b)
}
func (m *CombatGetInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatGetInfoResp.Marshal(b, m, deterministic)
}
func (m *CombatGetInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatGetInfoResp.Merge(m, src)
}
func (m *CombatGetInfoResp) XXX_Size() int {
	return xxx_messageInfo_CombatGetInfoResp.Size(m)
}
func (m *CombatGetInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatGetInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_CombatGetInfoResp proto.InternalMessageInfo

func (m *CombatGetInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatGetInfoResp) GetPlayerInitList() []*PlayerInit {
	if m != nil {
		return m.PlayerInitList
	}
	return nil
}

type CombatHeroMoveReq struct {
	TargetPos            *Vector3DTO `protobuf:"bytes,1,opt,name=targetPos,proto3" json:"targetPos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CombatHeroMoveReq) Reset()         { *m = CombatHeroMoveReq{} }
func (m *CombatHeroMoveReq) String() string { return proto.CompactTextString(m) }
func (*CombatHeroMoveReq) ProtoMessage()    {}
func (*CombatHeroMoveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{2}
}

func (m *CombatHeroMoveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroMoveReq.Unmarshal(m, b)
}
func (m *CombatHeroMoveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroMoveReq.Marshal(b, m, deterministic)
}
func (m *CombatHeroMoveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroMoveReq.Merge(m, src)
}
func (m *CombatHeroMoveReq) XXX_Size() int {
	return xxx_messageInfo_CombatHeroMoveReq.Size(m)
}
func (m *CombatHeroMoveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroMoveReq.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroMoveReq proto.InternalMessageInfo

func (m *CombatHeroMoveReq) GetTargetPos() *Vector3DTO {
	if m != nil {
		return m.TargetPos
	}
	return nil
}

type CombatHeroMoveResp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UserId               int32       `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string      `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	TargetPos            *Vector3DTO `protobuf:"bytes,4,opt,name=targetPos,proto3" json:"targetPos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CombatHeroMoveResp) Reset()         { *m = CombatHeroMoveResp{} }
func (m *CombatHeroMoveResp) String() string { return proto.CompactTextString(m) }
func (*CombatHeroMoveResp) ProtoMessage()    {}
func (*CombatHeroMoveResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{3}
}

func (m *CombatHeroMoveResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroMoveResp.Unmarshal(m, b)
}
func (m *CombatHeroMoveResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroMoveResp.Marshal(b, m, deterministic)
}
func (m *CombatHeroMoveResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroMoveResp.Merge(m, src)
}
func (m *CombatHeroMoveResp) XXX_Size() int {
	return xxx_messageInfo_CombatHeroMoveResp.Size(m)
}
func (m *CombatHeroMoveResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroMoveResp.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroMoveResp proto.InternalMessageInfo

func (m *CombatHeroMoveResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroMoveResp) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CombatHeroMoveResp) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CombatHeroMoveResp) GetTargetPos() *Vector3DTO {
	if m != nil {
		return m.TargetPos
	}
	return nil
}

type CombatHeroSkillReq struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroSkillReq) Reset()         { *m = CombatHeroSkillReq{} }
func (m *CombatHeroSkillReq) String() string { return proto.CompactTextString(m) }
func (*CombatHeroSkillReq) ProtoMessage()    {}
func (*CombatHeroSkillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{4}
}

func (m *CombatHeroSkillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroSkillReq.Unmarshal(m, b)
}
func (m *CombatHeroSkillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroSkillReq.Marshal(b, m, deterministic)
}
func (m *CombatHeroSkillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroSkillReq.Merge(m, src)
}
func (m *CombatHeroSkillReq) XXX_Size() int {
	return xxx_messageInfo_CombatHeroSkillReq.Size(m)
}
func (m *CombatHeroSkillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroSkillReq.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroSkillReq proto.InternalMessageInfo

func (m *CombatHeroSkillReq) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroSkillReq) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type CombatHeroSkillResp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroSkillResp) Reset()         { *m = CombatHeroSkillResp{} }
func (m *CombatHeroSkillResp) String() string { return proto.CompactTextString(m) }
func (*CombatHeroSkillResp) ProtoMessage()    {}
func (*CombatHeroSkillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{5}
}

func (m *CombatHeroSkillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroSkillResp.Unmarshal(m, b)
}
func (m *CombatHeroSkillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroSkillResp.Marshal(b, m, deterministic)
}
func (m *CombatHeroSkillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroSkillResp.Merge(m, src)
}
func (m *CombatHeroSkillResp) XXX_Size() int {
	return xxx_messageInfo_CombatHeroSkillResp.Size(m)
}
func (m *CombatHeroSkillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroSkillResp.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroSkillResp proto.InternalMessageInfo

func (m *CombatHeroSkillResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroSkillResp) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type CombatHeroEffectReq struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroEffectReq) Reset()         { *m = CombatHeroEffectReq{} }
func (m *CombatHeroEffectReq) String() string { return proto.CompactTextString(m) }
func (*CombatHeroEffectReq) ProtoMessage()    {}
func (*CombatHeroEffectReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{6}
}

func (m *CombatHeroEffectReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroEffectReq.Unmarshal(m, b)
}
func (m *CombatHeroEffectReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroEffectReq.Marshal(b, m, deterministic)
}
func (m *CombatHeroEffectReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroEffectReq.Merge(m, src)
}
func (m *CombatHeroEffectReq) XXX_Size() int {
	return xxx_messageInfo_CombatHeroEffectReq.Size(m)
}
func (m *CombatHeroEffectReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroEffectReq.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroEffectReq proto.InternalMessageInfo

func (m *CombatHeroEffectReq) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroEffectReq) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type CombatHeroEffectResp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroEffectResp) Reset()         { *m = CombatHeroEffectResp{} }
func (m *CombatHeroEffectResp) String() string { return proto.CompactTextString(m) }
func (*CombatHeroEffectResp) ProtoMessage()    {}
func (*CombatHeroEffectResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{7}
}

func (m *CombatHeroEffectResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroEffectResp.Unmarshal(m, b)
}
func (m *CombatHeroEffectResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroEffectResp.Marshal(b, m, deterministic)
}
func (m *CombatHeroEffectResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroEffectResp.Merge(m, src)
}
func (m *CombatHeroEffectResp) XXX_Size() int {
	return xxx_messageInfo_CombatHeroEffectResp.Size(m)
}
func (m *CombatHeroEffectResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroEffectResp.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroEffectResp proto.InternalMessageInfo

func (m *CombatHeroEffectResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroEffectResp) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type CombatHeroDeadReq struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroDeadReq) Reset()         { *m = CombatHeroDeadReq{} }
func (m *CombatHeroDeadReq) String() string { return proto.CompactTextString(m) }
func (*CombatHeroDeadReq) ProtoMessage()    {}
func (*CombatHeroDeadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{8}
}

func (m *CombatHeroDeadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroDeadReq.Unmarshal(m, b)
}
func (m *CombatHeroDeadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroDeadReq.Marshal(b, m, deterministic)
}
func (m *CombatHeroDeadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroDeadReq.Merge(m, src)
}
func (m *CombatHeroDeadReq) XXX_Size() int {
	return xxx_messageInfo_CombatHeroDeadReq.Size(m)
}
func (m *CombatHeroDeadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroDeadReq.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroDeadReq proto.InternalMessageInfo

func (m *CombatHeroDeadReq) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroDeadReq) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type CombatHeroDeadResp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CombatHeroDeadResp) Reset()         { *m = CombatHeroDeadResp{} }
func (m *CombatHeroDeadResp) String() string { return proto.CompactTextString(m) }
func (*CombatHeroDeadResp) ProtoMessage()    {}
func (*CombatHeroDeadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_951326dfcda18e27, []int{9}
}

func (m *CombatHeroDeadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CombatHeroDeadResp.Unmarshal(m, b)
}
func (m *CombatHeroDeadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CombatHeroDeadResp.Marshal(b, m, deterministic)
}
func (m *CombatHeroDeadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CombatHeroDeadResp.Merge(m, src)
}
func (m *CombatHeroDeadResp) XXX_Size() int {
	return xxx_messageInfo_CombatHeroDeadResp.Size(m)
}
func (m *CombatHeroDeadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CombatHeroDeadResp.DiscardUnknown(m)
}

var xxx_messageInfo_CombatHeroDeadResp proto.InternalMessageInfo

func (m *CombatHeroDeadResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CombatHeroDeadResp) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*CombatGetInfoReq)(nil), "prt.CombatGetInfoReq")
	proto.RegisterType((*CombatGetInfoResp)(nil), "prt.CombatGetInfoResp")
	proto.RegisterType((*CombatHeroMoveReq)(nil), "prt.CombatHeroMoveReq")
	proto.RegisterType((*CombatHeroMoveResp)(nil), "prt.CombatHeroMoveResp")
	proto.RegisterType((*CombatHeroSkillReq)(nil), "prt.CombatHeroSkillReq")
	proto.RegisterType((*CombatHeroSkillResp)(nil), "prt.CombatHeroSkillResp")
	proto.RegisterType((*CombatHeroEffectReq)(nil), "prt.CombatHeroEffectReq")
	proto.RegisterType((*CombatHeroEffectResp)(nil), "prt.CombatHeroEffectResp")
	proto.RegisterType((*CombatHeroDeadReq)(nil), "prt.CombatHeroDeadReq")
	proto.RegisterType((*CombatHeroDeadResp)(nil), "prt.CombatHeroDeadResp")
}

func init() { proto.RegisterFile("combat.proto", fileDescriptor_951326dfcda18e27) }

var fileDescriptor_951326dfcda18e27 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x86, 0x53, 0x5a, 0x89, 0x4c, 0xfd, 0x5c, 0x8d, 0x69, 0x38, 0xd5, 0x9e, 0x7a, 0xb1, 0x07,
	0x38, 0x78, 0x17, 0x8c, 0x56, 0x41, 0xc9, 0x6a, 0x3c, 0x5b, 0xda, 0xa9, 0x69, 0x6c, 0x99, 0xb2,
	0x5d, 0x4d, 0xfc, 0x0d, 0xfe, 0x69, 0xd3, 0x45, 0x04, 0x8a, 0xc4, 0x08, 0xb7, 0x99, 0x77, 0x26,
	0xef, 0x3c, 0xb3, 0x1f, 0xb0, 0x13, 0x52, 0x36, 0x0c, 0xa4, 0x97, 0x0b, 0x92, 0xc4, 0xf4, 0x5c,
	0xc8, 0xa6, 0x99, 0x51, 0x84, 0xe9, 0x44, 0x71, 0x18, 0x1c, 0x74, 0x54, 0xc7, 0x15, 0x4a, 0x7f,
	0x14, 0x13, 0xc7, 0xb1, 0xf3, 0x0c, 0x87, 0x15, 0xad, 0xc8, 0x19, 0x03, 0xa3, 0x43, 0x11, 0x5a,
	0x9a, 0xad, 0xb9, 0x5b, 0x5c, 0xc5, 0xec, 0x1c, 0xf6, 0x06, 0x69, 0xf0, 0x81, 0xc2, 0x1f, 0x25,
	0xb2, 0x97, 0x14, 0xd2, 0xaa, 0xd9, 0xba, 0x6b, 0xb6, 0xf6, 0xbd, 0x5c, 0x48, 0x6f, 0x56, 0xe2,
	0x95, 0x36, 0xe7, 0x62, 0x3a, 0xe1, 0x1a, 0x05, 0xf5, 0xe9, 0x1d, 0x39, 0x8e, 0xd9, 0x19, 0x34,
	0x64, 0x20, 0x5e, 0x50, 0x0e, 0xa8, 0x50, 0x63, 0xa6, 0x46, 0x4f, 0x18, 0x4a, 0x12, 0xed, 0xee,
	0xe3, 0x3d, 0x9f, 0x75, 0x38, 0x9f, 0x1a, 0xb0, 0xaa, 0xc9, 0x0a, 0xce, 0x13, 0xa8, 0xbf, 0x15,
	0x28, 0xfc, 0xc8, 0xaa, 0x29, 0xf5, 0x3b, 0x63, 0x4d, 0xd8, 0x2e, 0xa3, 0xbb, 0x20, 0x43, 0x4b,
	0xb7, 0x35, 0xb7, 0xc1, 0x7f, 0xf2, 0x45, 0x1a, 0xe3, 0x4f, 0x9a, 0xdb, 0x79, 0x98, 0x87, 0xd7,
	0x24, 0x4d, 0xcb, 0x95, 0x7e, 0x83, 0x39, 0x05, 0x83, 0x13, 0x65, 0x0a, 0xc5, 0x6c, 0xed, 0x2a,
	0xcf, 0x52, 0x50, 0x27, 0xad, 0x4a, 0x4e, 0x0f, 0x8e, 0x96, 0xcc, 0x56, 0xac, 0xf6, 0x5f, 0xb7,
	0xcb, 0x38, 0xc6, 0x50, 0x6e, 0xc0, 0xd6, 0x87, 0xe3, 0x65, 0xb7, 0xf5, 0xe1, 0x6e, 0xe6, 0x5f,
	0x42, 0x17, 0x83, 0x68, 0x03, 0xb4, 0x85, 0x3b, 0x98, 0x78, 0xad, 0x0d, 0x36, 0xac, 0xab, 0xff,
	0xd1, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x12, 0x26, 0xe0, 0x92, 0x41, 0x03, 0x00, 0x00,
}
