// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ready.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetReadyInfoReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReadyInfoReq) Reset()         { *m = GetReadyInfoReq{} }
func (m *GetReadyInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetReadyInfoReq) ProtoMessage()    {}
func (*GetReadyInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2508f16030f10f, []int{0}
}

func (m *GetReadyInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReadyInfoReq.Unmarshal(m, b)
}
func (m *GetReadyInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReadyInfoReq.Marshal(b, m, deterministic)
}
func (m *GetReadyInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReadyInfoReq.Merge(m, src)
}
func (m *GetReadyInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetReadyInfoReq.Size(m)
}
func (m *GetReadyInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReadyInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReadyInfoReq proto.InternalMessageInfo

type GetReadyInfoResp struct {
	Code int32 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	//repeated Player PlayerList = 3;
	UserList             []*UserInfo `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetReadyInfoResp) Reset()         { *m = GetReadyInfoResp{} }
func (m *GetReadyInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetReadyInfoResp) ProtoMessage()    {}
func (*GetReadyInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2508f16030f10f, []int{1}
}

func (m *GetReadyInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReadyInfoResp.Unmarshal(m, b)
}
func (m *GetReadyInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReadyInfoResp.Marshal(b, m, deterministic)
}
func (m *GetReadyInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReadyInfoResp.Merge(m, src)
}
func (m *GetReadyInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetReadyInfoResp.Size(m)
}
func (m *GetReadyInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReadyInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetReadyInfoResp proto.InternalMessageInfo

func (m *GetReadyInfoResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetReadyInfoResp) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

type PrepareCombatReq struct {
	WeaponExtraAttrList  []*WeaponExtraAttr `protobuf:"bytes,1,rep,name=WeaponExtraAttrList,proto3" json:"WeaponExtraAttrList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PrepareCombatReq) Reset()         { *m = PrepareCombatReq{} }
func (m *PrepareCombatReq) String() string { return proto.CompactTextString(m) }
func (*PrepareCombatReq) ProtoMessage()    {}
func (*PrepareCombatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2508f16030f10f, []int{2}
}

func (m *PrepareCombatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareCombatReq.Unmarshal(m, b)
}
func (m *PrepareCombatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareCombatReq.Marshal(b, m, deterministic)
}
func (m *PrepareCombatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareCombatReq.Merge(m, src)
}
func (m *PrepareCombatReq) XXX_Size() int {
	return xxx_messageInfo_PrepareCombatReq.Size(m)
}
func (m *PrepareCombatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareCombatReq.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareCombatReq proto.InternalMessageInfo

func (m *PrepareCombatReq) GetWeaponExtraAttrList() []*WeaponExtraAttr {
	if m != nil {
		return m.WeaponExtraAttrList
	}
	return nil
}

type PrepareCombatResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareCombatResp) Reset()         { *m = PrepareCombatResp{} }
func (m *PrepareCombatResp) String() string { return proto.CompactTextString(m) }
func (*PrepareCombatResp) ProtoMessage()    {}
func (*PrepareCombatResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2508f16030f10f, []int{3}
}

func (m *PrepareCombatResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareCombatResp.Unmarshal(m, b)
}
func (m *PrepareCombatResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareCombatResp.Marshal(b, m, deterministic)
}
func (m *PrepareCombatResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareCombatResp.Merge(m, src)
}
func (m *PrepareCombatResp) XXX_Size() int {
	return xxx_messageInfo_PrepareCombatResp.Size(m)
}
func (m *PrepareCombatResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareCombatResp.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareCombatResp proto.InternalMessageInfo

func (m *PrepareCombatResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*GetReadyInfoReq)(nil), "prt.GetReadyInfoReq")
	proto.RegisterType((*GetReadyInfoResp)(nil), "prt.GetReadyInfoResp")
	proto.RegisterType((*PrepareCombatReq)(nil), "prt.PrepareCombatReq")
	proto.RegisterType((*PrepareCombatResp)(nil), "prt.PrepareCombatResp")
}

func init() { proto.RegisterFile("ready.proto", fileDescriptor_5d2508f16030f10f) }

var fileDescriptor_5d2508f16030f10f = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0x4d, 0x4c,
	0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x28, 0x2a, 0x91, 0xe2, 0xce, 0xcd,
	0x4f, 0x49, 0xcd, 0x81, 0x88, 0x28, 0x09, 0x72, 0xf1, 0xbb, 0xa7, 0x96, 0x04, 0x81, 0xd4, 0x78,
	0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x2a, 0x05, 0x72, 0x09, 0xa0, 0x0a, 0x15, 0x17, 0x08, 0x09,
	0x71, 0xb1, 0x38, 0xe7, 0xa7, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x42,
	0x9a, 0x5c, 0x1c, 0xa1, 0xc5, 0xa9, 0x45, 0x3e, 0x99, 0xc5, 0x25, 0x12, 0x4c, 0x0a, 0xcc, 0x1a,
	0xdc, 0x46, 0xbc, 0x7a, 0x05, 0x45, 0x25, 0x7a, 0x20, 0x41, 0xb0, 0x46, 0xb8, 0xb4, 0x52, 0x14,
	0x97, 0x40, 0x40, 0x51, 0x6a, 0x41, 0x62, 0x51, 0xaa, 0x73, 0x7e, 0x6e, 0x52, 0x62, 0x49, 0x50,
	0x6a, 0xa1, 0x90, 0x1b, 0x97, 0x70, 0x78, 0x6a, 0x62, 0x41, 0x7e, 0x9e, 0x6b, 0x45, 0x49, 0x51,
	0xa2, 0x63, 0x49, 0x09, 0xc4, 0x24, 0x46, 0xb0, 0x49, 0x22, 0x60, 0x93, 0xd0, 0xe4, 0x83, 0xb0,
	0x69, 0x50, 0x52, 0xe7, 0x12, 0x44, 0x33, 0x1b, 0xbb, 0x7b, 0x93, 0xd8, 0xc0, 0x3e, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x68, 0xc0, 0x3f, 0x42, 0x12, 0x01, 0x00, 0x00,
}
