// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mj.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MJ int32

const (
	MJ_A MJ = 0
	MJ_B MJ = 1
	MJ_C MJ = 2
)

var MJ_name = map[int32]string{
	0: "A",
	1: "B",
	2: "C",
}

var MJ_value = map[string]int32{
	"A": 0,
	"B": 1,
	"C": 2,
}

func (x MJ) String() string {
	return proto.EnumName(MJ_name, int32(x))
}

func (MJ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_907628aa8f7c60c7, []int{0}
}

func init() {
	proto.RegisterEnum("auth.MJ", MJ_name, MJ_value)
}

func init() { proto.RegisterFile("mj.proto", fileDescriptor_907628aa8f7c60c7) }

var fileDescriptor_907628aa8f7c60c7 = []byte{
	// 67 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xcd, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9, 0xd0, 0x92, 0xe4, 0x62, 0xf2, 0xf5,
	0x12, 0x62, 0xe5, 0x62, 0x74, 0x14, 0x60, 0x00, 0x51, 0x4e, 0x02, 0x8c, 0x20, 0xca, 0x59, 0x80,
	0x29, 0x89, 0x0d, 0xac, 0xce, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x17, 0xb9, 0xba, 0x33,
	0x00, 0x00, 0x00,
}
