// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dto.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInfoDTO struct {
	ID                   int32          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserList             []*UserInfoDTO `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomInfoDTO) Reset()         { *m = RoomInfoDTO{} }
func (m *RoomInfoDTO) String() string { return proto.CompactTextString(m) }
func (*RoomInfoDTO) ProtoMessage()    {}
func (*RoomInfoDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{0}
}

func (m *RoomInfoDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfoDTO.Unmarshal(m, b)
}
func (m *RoomInfoDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfoDTO.Marshal(b, m, deterministic)
}
func (m *RoomInfoDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfoDTO.Merge(m, src)
}
func (m *RoomInfoDTO) XXX_Size() int {
	return xxx_messageInfo_RoomInfoDTO.Size(m)
}
func (m *RoomInfoDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfoDTO.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfoDTO proto.InternalMessageInfo

func (m *RoomInfoDTO) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoomInfoDTO) GetUserList() []*UserInfoDTO {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserInfoDTO struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	IconURL              string   `protobuf:"bytes,2,opt,name=IconURL,proto3" json:"IconURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoDTO) Reset()         { *m = UserInfoDTO{} }
func (m *UserInfoDTO) String() string { return proto.CompactTextString(m) }
func (*UserInfoDTO) ProtoMessage()    {}
func (*UserInfoDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{1}
}

func (m *UserInfoDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoDTO.Unmarshal(m, b)
}
func (m *UserInfoDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoDTO.Marshal(b, m, deterministic)
}
func (m *UserInfoDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoDTO.Merge(m, src)
}
func (m *UserInfoDTO) XXX_Size() int {
	return xxx_messageInfo_UserInfoDTO.Size(m)
}
func (m *UserInfoDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoDTO.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoDTO proto.InternalMessageInfo

func (m *UserInfoDTO) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoDTO) GetIconURL() string {
	if m != nil {
		return m.IconURL
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomInfoDTO)(nil), "prt.RoomInfoDTO")
	proto.RegisterType((*UserInfoDTO)(nil), "prt.UserInfoDTO")
}

func init() { proto.RegisterFile("dto.proto", fileDescriptor_3b9f020a7bf4eafc) }

var fileDescriptor_3b9f020a7bf4eafc = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x29, 0xc9, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x28, 0x2a, 0x51, 0xf2, 0xe6, 0xe2, 0x0e, 0xca,
	0xcf, 0xcf, 0xf5, 0xcc, 0x4b, 0xcb, 0x77, 0x09, 0xf1, 0x17, 0xe2, 0xe3, 0x62, 0xf2, 0x74, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xf2, 0x74, 0x11, 0xd2, 0xe1, 0xe2, 0x08, 0x2d, 0x4e,
	0x2d, 0xf2, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x36, 0x12, 0xd0, 0x2b, 0x28,
	0x2a, 0xd1, 0x03, 0x09, 0x42, 0xf5, 0x04, 0xc1, 0x55, 0x28, 0x39, 0x73, 0x71, 0x23, 0x49, 0x08,
	0x49, 0x41, 0x34, 0xfb, 0x25, 0xe6, 0xa6, 0x82, 0x8d, 0xe4, 0x0c, 0x82, 0xf3, 0x85, 0x24, 0xb8,
	0xd8, 0x3d, 0x93, 0xf3, 0xf3, 0x42, 0x83, 0x7c, 0x24, 0x98, 0xc0, 0x52, 0x30, 0x6e, 0x12, 0x1b,
	0xd8, 0x75, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x7d, 0x86, 0x18, 0xaa, 0x00, 0x00,
	0x00,
}
