// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dto.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInfoDTO struct {
	ID                   int32          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserList             []*UserInfoDTO `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RoomInfoDTO) Reset()         { *m = RoomInfoDTO{} }
func (m *RoomInfoDTO) String() string { return proto.CompactTextString(m) }
func (*RoomInfoDTO) ProtoMessage()    {}
func (*RoomInfoDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{0}
}

func (m *RoomInfoDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfoDTO.Unmarshal(m, b)
}
func (m *RoomInfoDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfoDTO.Marshal(b, m, deterministic)
}
func (m *RoomInfoDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfoDTO.Merge(m, src)
}
func (m *RoomInfoDTO) XXX_Size() int {
	return xxx_messageInfo_RoomInfoDTO.Size(m)
}
func (m *RoomInfoDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfoDTO.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfoDTO proto.InternalMessageInfo

func (m *RoomInfoDTO) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoomInfoDTO) GetUserList() []*UserInfoDTO {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserInfoDTO struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	IconURL              string   `protobuf:"bytes,2,opt,name=IconURL,proto3" json:"IconURL,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoDTO) Reset()         { *m = UserInfoDTO{} }
func (m *UserInfoDTO) String() string { return proto.CompactTextString(m) }
func (*UserInfoDTO) ProtoMessage()    {}
func (*UserInfoDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{1}
}

func (m *UserInfoDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoDTO.Unmarshal(m, b)
}
func (m *UserInfoDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoDTO.Marshal(b, m, deterministic)
}
func (m *UserInfoDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoDTO.Merge(m, src)
}
func (m *UserInfoDTO) XXX_Size() int {
	return xxx_messageInfo_UserInfoDTO.Size(m)
}
func (m *UserInfoDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoDTO.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoDTO proto.InternalMessageInfo

func (m *UserInfoDTO) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfoDTO) GetIconURL() string {
	if m != nil {
		return m.IconURL
	}
	return ""
}

type PlayerDTO struct {
	UserID               int32      `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Weapon               *WeaponDTO `protobuf:"bytes,2,opt,name=Weapon,proto3" json:"Weapon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayerDTO) Reset()         { *m = PlayerDTO{} }
func (m *PlayerDTO) String() string { return proto.CompactTextString(m) }
func (*PlayerDTO) ProtoMessage()    {}
func (*PlayerDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{2}
}

func (m *PlayerDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDTO.Unmarshal(m, b)
}
func (m *PlayerDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDTO.Marshal(b, m, deterministic)
}
func (m *PlayerDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDTO.Merge(m, src)
}
func (m *PlayerDTO) XXX_Size() int {
	return xxx_messageInfo_PlayerDTO.Size(m)
}
func (m *PlayerDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDTO.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDTO proto.InternalMessageInfo

func (m *PlayerDTO) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *PlayerDTO) GetWeapon() *WeaponDTO {
	if m != nil {
		return m.Weapon
	}
	return nil
}

type WeaponDTO struct {
	ID                   int32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SN                   int32                 `protobuf:"varint,2,opt,name=SN,proto3" json:"SN,omitempty"`
	WeaponList           []*WeaponExtraAttrDTO `protobuf:"bytes,3,rep,name=WeaponList,proto3" json:"WeaponList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *WeaponDTO) Reset()         { *m = WeaponDTO{} }
func (m *WeaponDTO) String() string { return proto.CompactTextString(m) }
func (*WeaponDTO) ProtoMessage()    {}
func (*WeaponDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{3}
}

func (m *WeaponDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeaponDTO.Unmarshal(m, b)
}
func (m *WeaponDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeaponDTO.Marshal(b, m, deterministic)
}
func (m *WeaponDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeaponDTO.Merge(m, src)
}
func (m *WeaponDTO) XXX_Size() int {
	return xxx_messageInfo_WeaponDTO.Size(m)
}
func (m *WeaponDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_WeaponDTO.DiscardUnknown(m)
}

var xxx_messageInfo_WeaponDTO proto.InternalMessageInfo

func (m *WeaponDTO) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *WeaponDTO) GetSN() int32 {
	if m != nil {
		return m.SN
	}
	return 0
}

func (m *WeaponDTO) GetWeaponList() []*WeaponExtraAttrDTO {
	if m != nil {
		return m.WeaponList
	}
	return nil
}

type WeaponExtraAttrDTO struct {
	AttrType             int32    `protobuf:"varint,1,opt,name=attrType,proto3" json:"attrType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeaponExtraAttrDTO) Reset()         { *m = WeaponExtraAttrDTO{} }
func (m *WeaponExtraAttrDTO) String() string { return proto.CompactTextString(m) }
func (*WeaponExtraAttrDTO) ProtoMessage()    {}
func (*WeaponExtraAttrDTO) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b9f020a7bf4eafc, []int{4}
}

func (m *WeaponExtraAttrDTO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeaponExtraAttrDTO.Unmarshal(m, b)
}
func (m *WeaponExtraAttrDTO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeaponExtraAttrDTO.Marshal(b, m, deterministic)
}
func (m *WeaponExtraAttrDTO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeaponExtraAttrDTO.Merge(m, src)
}
func (m *WeaponExtraAttrDTO) XXX_Size() int {
	return xxx_messageInfo_WeaponExtraAttrDTO.Size(m)
}
func (m *WeaponExtraAttrDTO) XXX_DiscardUnknown() {
	xxx_messageInfo_WeaponExtraAttrDTO.DiscardUnknown(m)
}

var xxx_messageInfo_WeaponExtraAttrDTO proto.InternalMessageInfo

func (m *WeaponExtraAttrDTO) GetAttrType() int32 {
	if m != nil {
		return m.AttrType
	}
	return 0
}

func (m *WeaponExtraAttrDTO) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*RoomInfoDTO)(nil), "prt.RoomInfoDTO")
	proto.RegisterType((*UserInfoDTO)(nil), "prt.UserInfoDTO")
	proto.RegisterType((*PlayerDTO)(nil), "prt.PlayerDTO")
	proto.RegisterType((*WeaponDTO)(nil), "prt.WeaponDTO")
	proto.RegisterType((*WeaponExtraAttrDTO)(nil), "prt.WeaponExtraAttrDTO")
}

func init() { proto.RegisterFile("dto.proto", fileDescriptor_3b9f020a7bf4eafc) }

var fileDescriptor_3b9f020a7bf4eafc = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x66, 0x29, 0xad, 0xf6, 0x15, 0x8a, 0x04, 0xd1, 0xe2, 0x69, 0xe4, 0x20, 0x3b, 0x48, 0x0f,
	0xf3, 0xe0, 0x59, 0xac, 0x42, 0xd9, 0xa8, 0x92, 0x6d, 0x78, 0x8e, 0x2e, 0x82, 0xb0, 0x35, 0x21,
	0x7b, 0x8a, 0xfb, 0xef, 0x25, 0xaf, 0x59, 0x29, 0xf4, 0xf8, 0xbd, 0xef, 0x47, 0xbe, 0x8f, 0x40,
	0xba, 0x45, 0x53, 0x5a, 0x67, 0xd0, 0xf0, 0xc8, 0x3a, 0x14, 0x0b, 0xc8, 0xa4, 0x31, 0xfb, 0xba,
	0xfd, 0x32, 0xd5, 0xfa, 0x95, 0xe7, 0xc0, 0xea, 0xaa, 0x98, 0x4c, 0x27, 0xb3, 0x58, 0xb2, 0xba,
	0xe2, 0x77, 0x70, 0xbe, 0x39, 0x68, 0xb7, 0xfc, 0x3e, 0x60, 0xc1, 0xa6, 0xd1, 0x2c, 0x9b, 0x5f,
	0x94, 0xd6, 0x61, 0xe9, 0x8f, 0xc1, 0x23, 0x7b, 0x85, 0x78, 0x82, 0x6c, 0x40, 0xf0, 0x9b, 0xce,
	0xdc, 0xa8, 0xbd, 0xa6, 0xc8, 0x54, 0xf6, 0x98, 0x17, 0x70, 0x56, 0x7f, 0x9a, 0x76, 0x23, 0x97,
	0x05, 0x23, 0xea, 0x04, 0xc5, 0x02, 0xd2, 0xb7, 0x9d, 0x3a, 0x6a, 0xe7, 0x23, 0xae, 0x20, 0xa1,
	0xc4, 0x53, 0xa7, 0x80, 0xf8, 0x2d, 0x24, 0xef, 0x5a, 0x59, 0xd3, 0x92, 0x3b, 0x9b, 0xe7, 0xd4,
	0xaa, 0x3b, 0xf9, 0x4e, 0x81, 0x15, 0x5b, 0x48, 0xfb, 0xe3, 0x68, 0x5c, 0x0e, 0x6c, 0xd5, 0x50,
	0x40, 0x2c, 0xd9, 0xaa, 0xe1, 0x0f, 0x00, 0x9d, 0x98, 0xe6, 0x46, 0x34, 0xf7, 0x7a, 0x10, 0xfc,
	0xfc, 0x87, 0x4e, 0x3d, 0x22, 0xfa, 0x66, 0x72, 0x20, 0x15, 0x2f, 0xc0, 0xc7, 0x0a, 0x3f, 0x5f,
	0x21, 0xba, 0xf5, 0xd1, 0xea, 0xf0, 0x68, 0x8f, 0xf9, 0x25, 0xc4, 0xbf, 0x6a, 0xf7, 0xa3, 0xc3,
	0xeb, 0x1d, 0xf8, 0x48, 0xe8, 0x63, 0xee, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0xab, 0x09, 0x3f,
	0xb3, 0xa5, 0x01, 0x00, 0x00,
}
