// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInfo struct {
	ID                   int32       `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserList             []*UserInfo `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *RoomInfo) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

type UserInfo struct {
	UserName             string   `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	IconURL              string   `protobuf:"bytes,2,opt,name=IconURL,proto3" json:"IconURL,omitempty"`
	Weapon               *Weapon  `protobuf:"bytes,3,opt,name=Weapon,proto3" json:"Weapon,omitempty"`
	AttributeNum         int32    `protobuf:"varint,4,opt,name=AttributeNum,proto3" json:"AttributeNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetIconURL() string {
	if m != nil {
		return m.IconURL
	}
	return ""
}

func (m *UserInfo) GetWeapon() *Weapon {
	if m != nil {
		return m.Weapon
	}
	return nil
}

func (m *UserInfo) GetAttributeNum() int32 {
	if m != nil {
		return m.AttributeNum
	}
	return 0
}

type Weapon struct {
	ID                   int32              `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SN                   int32              `protobuf:"varint,2,opt,name=SN,proto3" json:"SN,omitempty"`
	WeaponExtraAttrList  []*WeaponExtraAttr `protobuf:"bytes,3,rep,name=WeaponExtraAttrList,proto3" json:"WeaponExtraAttrList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Weapon) Reset()         { *m = Weapon{} }
func (m *Weapon) String() string { return proto.CompactTextString(m) }
func (*Weapon) ProtoMessage()    {}
func (*Weapon) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *Weapon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Weapon.Unmarshal(m, b)
}
func (m *Weapon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Weapon.Marshal(b, m, deterministic)
}
func (m *Weapon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Weapon.Merge(m, src)
}
func (m *Weapon) XXX_Size() int {
	return xxx_messageInfo_Weapon.Size(m)
}
func (m *Weapon) XXX_DiscardUnknown() {
	xxx_messageInfo_Weapon.DiscardUnknown(m)
}

var xxx_messageInfo_Weapon proto.InternalMessageInfo

func (m *Weapon) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Weapon) GetSN() int32 {
	if m != nil {
		return m.SN
	}
	return 0
}

func (m *Weapon) GetWeaponExtraAttrList() []*WeaponExtraAttr {
	if m != nil {
		return m.WeaponExtraAttrList
	}
	return nil
}

type WeaponExtraAttr struct {
	AttrType             int32    `protobuf:"varint,1,opt,name=AttrType,proto3" json:"AttrType,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeaponExtraAttr) Reset()         { *m = WeaponExtraAttr{} }
func (m *WeaponExtraAttr) String() string { return proto.CompactTextString(m) }
func (*WeaponExtraAttr) ProtoMessage()    {}
func (*WeaponExtraAttr) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *WeaponExtraAttr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeaponExtraAttr.Unmarshal(m, b)
}
func (m *WeaponExtraAttr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeaponExtraAttr.Marshal(b, m, deterministic)
}
func (m *WeaponExtraAttr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeaponExtraAttr.Merge(m, src)
}
func (m *WeaponExtraAttr) XXX_Size() int {
	return xxx_messageInfo_WeaponExtraAttr.Size(m)
}
func (m *WeaponExtraAttr) XXX_DiscardUnknown() {
	xxx_messageInfo_WeaponExtraAttr.DiscardUnknown(m)
}

var xxx_messageInfo_WeaponExtraAttr proto.InternalMessageInfo

func (m *WeaponExtraAttr) GetAttrType() int32 {
	if m != nil {
		return m.AttrType
	}
	return 0
}

func (m *WeaponExtraAttr) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*RoomInfo)(nil), "prt.RoomInfo")
	proto.RegisterType((*UserInfo)(nil), "prt.UserInfo")
	proto.RegisterType((*Weapon)(nil), "prt.Weapon")
	proto.RegisterType((*WeaponExtraAttr)(nil), "prt.WeaponExtraAttr")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x1c, 0x52, 0xca, 0x06, 0x8a, 0x64, 0x7a, 0xb0, 0x38, 0x45, 0xe6, 0x12, 0x2e, 0x39,
	0x94, 0x2f, 0x40, 0xb4, 0x48, 0x91, 0xaa, 0x1c, 0x5c, 0x0a, 0xe7, 0x14, 0x8c, 0x54, 0xa9, 0x89,
	0x2d, 0x77, 0x23, 0xc1, 0x27, 0xf0, 0xd7, 0xc8, 0xeb, 0x34, 0xe2, 0xd1, 0x93, 0x3d, 0x33, 0xbb,
	0xb3, 0x3b, 0x36, 0xa4, 0x8d, 0x79, 0xd3, 0xbb, 0xc2, 0x3a, 0x83, 0x86, 0xc7, 0xd6, 0xa1, 0x5c,
	0xc0, 0x58, 0x19, 0xd3, 0x94, 0xed, 0xbb, 0xe1, 0x13, 0x60, 0xe5, 0x5c, 0x44, 0x59, 0x94, 0x27,
	0x8a, 0x95, 0x73, 0x7e, 0x0b, 0xe3, 0xf5, 0x5e, 0xbb, 0xe5, 0x76, 0x8f, 0x82, 0x65, 0x71, 0x9e,
	0xce, 0x2e, 0x0a, 0xeb, 0xb0, 0xf0, 0xa4, 0x6f, 0x50, 0x83, 0x2c, 0xbf, 0xa2, 0x50, 0x4b, 0x3e,
	0xd7, 0xe1, 0x5e, 0xd5, 0x8d, 0x26, 0xb7, 0x33, 0x35, 0x60, 0x2e, 0xe0, 0xb4, 0x7c, 0x35, 0xed,
	0x5a, 0x2d, 0x05, 0x23, 0xe9, 0x00, 0xf9, 0x0d, 0x8c, 0x5e, 0x74, 0x6d, 0x4d, 0x2b, 0xe2, 0x2c,
	0xca, 0xd3, 0x59, 0x4a, 0xb3, 0x02, 0xa5, 0x7a, 0x89, 0x4b, 0x38, 0xbf, 0x47, 0x74, 0xdb, 0x4d,
	0x87, 0xba, 0xea, 0x1a, 0x71, 0x42, 0xcb, 0xfe, 0xe2, 0xa4, 0x3d, 0x18, 0xfd, 0x0b, 0x34, 0x01,
	0xb6, 0xaa, 0x68, 0x6e, 0xa2, 0xd8, 0xaa, 0xe2, 0x8f, 0x70, 0x15, 0x2a, 0x17, 0x1f, 0xe8, 0x6a,
	0x6f, 0x42, 0x59, 0x63, 0xca, 0x3a, 0xfd, 0x31, 0x7f, 0xd0, 0xd5, 0xb1, 0x06, 0xf9, 0x00, 0x97,
	0x7f, 0x68, 0xff, 0x06, 0xfe, 0x7c, 0xfa, 0xb4, 0xba, 0x5f, 0x60, 0xc0, 0x7c, 0x0a, 0xc9, 0x73,
	0xbd, 0xeb, 0x74, 0xbf, 0x49, 0x00, 0x9b, 0x11, 0xfd, 0xca, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0xc3, 0xae, 0xa6, 0xa4, 0x01, 0x00, 0x00,
}
