// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRoomListReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoomListReq) Reset()         { *m = QueryRoomListReq{} }
func (m *QueryRoomListReq) String() string { return proto.CompactTextString(m) }
func (*QueryRoomListReq) ProtoMessage()    {}
func (*QueryRoomListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *QueryRoomListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomListReq.Unmarshal(m, b)
}
func (m *QueryRoomListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomListReq.Marshal(b, m, deterministic)
}
func (m *QueryRoomListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomListReq.Merge(m, src)
}
func (m *QueryRoomListReq) XXX_Size() int {
	return xxx_messageInfo_QueryRoomListReq.Size(m)
}
func (m *QueryRoomListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomListReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomListReq proto.InternalMessageInfo

func (m *QueryRoomListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryRoomListReq) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type QueryRoomListResp struct {
	Code                 int32       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	RoomList             []*RoomInfo `protobuf:"bytes,2,rep,name=RoomList,proto3" json:"RoomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QueryRoomListResp) Reset()         { *m = QueryRoomListResp{} }
func (m *QueryRoomListResp) String() string { return proto.CompactTextString(m) }
func (*QueryRoomListResp) ProtoMessage()    {}
func (*QueryRoomListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *QueryRoomListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomListResp.Unmarshal(m, b)
}
func (m *QueryRoomListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomListResp.Marshal(b, m, deterministic)
}
func (m *QueryRoomListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomListResp.Merge(m, src)
}
func (m *QueryRoomListResp) XXX_Size() int {
	return xxx_messageInfo_QueryRoomListResp.Size(m)
}
func (m *QueryRoomListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomListResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomListResp proto.InternalMessageInfo

func (m *QueryRoomListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryRoomListResp) GetRoomList() []*RoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

type GetInRoomReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInRoomReq) Reset()         { *m = GetInRoomReq{} }
func (m *GetInRoomReq) String() string { return proto.CompactTextString(m) }
func (*GetInRoomReq) ProtoMessage()    {}
func (*GetInRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *GetInRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInRoomReq.Unmarshal(m, b)
}
func (m *GetInRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInRoomReq.Marshal(b, m, deterministic)
}
func (m *GetInRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInRoomReq.Merge(m, src)
}
func (m *GetInRoomReq) XXX_Size() int {
	return xxx_messageInfo_GetInRoomReq.Size(m)
}
func (m *GetInRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInRoomReq proto.InternalMessageInfo

func (m *GetInRoomReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetInRoomResp struct {
	Code                 int32     `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfo `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetInRoomResp) Reset()         { *m = GetInRoomResp{} }
func (m *GetInRoomResp) String() string { return proto.CompactTextString(m) }
func (*GetInRoomResp) ProtoMessage()    {}
func (*GetInRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *GetInRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInRoomResp.Unmarshal(m, b)
}
func (m *GetInRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInRoomResp.Marshal(b, m, deterministic)
}
func (m *GetInRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInRoomResp.Merge(m, src)
}
func (m *GetInRoomResp) XXX_Size() int {
	return xxx_messageInfo_GetInRoomResp.Size(m)
}
func (m *GetInRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInRoomResp proto.InternalMessageInfo

func (m *GetInRoomResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetInRoomResp) GetRoom() *RoomInfo {
	if m != nil {
		return m.Room
	}
	return nil
}

type EnterReadyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterReadyReq) Reset()         { *m = EnterReadyReq{} }
func (m *EnterReadyReq) String() string { return proto.CompactTextString(m) }
func (*EnterReadyReq) ProtoMessage()    {}
func (*EnterReadyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}

func (m *EnterReadyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterReadyReq.Unmarshal(m, b)
}
func (m *EnterReadyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterReadyReq.Marshal(b, m, deterministic)
}
func (m *EnterReadyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterReadyReq.Merge(m, src)
}
func (m *EnterReadyReq) XXX_Size() int {
	return xxx_messageInfo_EnterReadyReq.Size(m)
}
func (m *EnterReadyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterReadyReq.DiscardUnknown(m)
}

var xxx_messageInfo_EnterReadyReq proto.InternalMessageInfo

type EnterReadyResp struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterReadyResp) Reset()         { *m = EnterReadyResp{} }
func (m *EnterReadyResp) String() string { return proto.CompactTextString(m) }
func (*EnterReadyResp) ProtoMessage()    {}
func (*EnterReadyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{5}
}

func (m *EnterReadyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterReadyResp.Unmarshal(m, b)
}
func (m *EnterReadyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterReadyResp.Marshal(b, m, deterministic)
}
func (m *EnterReadyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterReadyResp.Merge(m, src)
}
func (m *EnterReadyResp) XXX_Size() int {
	return xxx_messageInfo_EnterReadyResp.Size(m)
}
func (m *EnterReadyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterReadyResp.DiscardUnknown(m)
}

var xxx_messageInfo_EnterReadyResp proto.InternalMessageInfo

func (m *EnterReadyResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryRoomListReq)(nil), "prt.QueryRoomListReq")
	proto.RegisterType((*QueryRoomListResp)(nil), "prt.QueryRoomListResp")
	proto.RegisterType((*GetInRoomReq)(nil), "prt.GetInRoomReq")
	proto.RegisterType((*GetInRoomResp)(nil), "prt.GetInRoomResp")
	proto.RegisterType((*EnterReadyReq)(nil), "prt.EnterReadyReq")
	proto.RegisterType((*EnterReadyResp)(nil), "prt.EnterReadyResp")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0x80, 0x40,
	0x10, 0x80, 0x71, 0xb5, 0xa8, 0x31, 0xad, 0xf6, 0x24, 0x11, 0x61, 0x4b, 0x07, 0xbb, 0x78, 0xa8,
	0x47, 0xd0, 0x8a, 0x85, 0x0e, 0xb5, 0x6f, 0x60, 0x38, 0x45, 0x90, 0x3b, 0xeb, 0xba, 0x1e, 0x7c,
	0xfb, 0xd8, 0xad, 0x4c, 0xfa, 0x39, 0x39, 0x7c, 0x9f, 0x7c, 0x33, 0x2c, 0x80, 0x25, 0x1a, 0x6a,
	0x63, 0xc9, 0x11, 0x8f, 0x8d, 0x75, 0x27, 0xe9, 0x40, 0x3d, 0xbe, 0x7d, 0x10, 0xd1, 0xc2, 0xd1,
	0xe3, 0x8c, 0x76, 0x51, 0x44, 0xc3, 0xfd, 0xeb, 0xe4, 0x14, 0x8e, 0x9c, 0x43, 0xf2, 0xd0, 0xbd,
	0x60, 0x11, 0x95, 0x51, 0xb5, 0xa3, 0xc2, 0xcc, 0x4f, 0x61, 0xdf, 0x7f, 0x1b, 0x9a, 0xb5, 0x2b,
	0x58, 0x10, 0xdf, 0x40, 0x28, 0x38, 0xfe, 0x51, 0x99, 0x8c, 0xcf, 0x34, 0xd4, 0xaf, 0x19, 0x3f,
	0xf3, 0x4b, 0xd8, 0xfb, 0xfa, 0xa7, 0x60, 0x65, 0x5c, 0xa5, 0x57, 0x59, 0x6d, 0xac, 0xab, 0x3d,
	0x94, 0xfa, 0x99, 0xd4, 0xaa, 0xc5, 0x19, 0x1c, 0xdc, 0xa1, 0x93, 0xda, 0x03, 0x7f, 0x55, 0x0e,
	0x4c, 0xb6, 0x9f, 0x31, 0x26, 0x5b, 0x71, 0x0b, 0xd9, 0xc6, 0xff, 0xb3, 0xef, 0x1c, 0x12, 0xef,
	0xc3, 0xc5, 0xbf, 0x76, 0x05, 0x25, 0x0e, 0x21, 0xbb, 0xd1, 0x0e, 0xad, 0xc2, 0xae, 0x5f, 0x14,
	0x8e, 0xe2, 0x02, 0xf2, 0x2d, 0xf8, 0xbb, 0xfc, 0xb4, 0x1b, 0xde, 0xef, 0xfa, 0x3d, 0x00, 0x00,
	0xff, 0xff, 0xe1, 0x10, 0x81, 0x89, 0x5f, 0x01, 0x00, 0x00,
}
