// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package prt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryRoomListReq struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageCount            int32    `protobuf:"varint,2,opt,name=PageCount,proto3" json:"PageCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRoomListReq) Reset()         { *m = QueryRoomListReq{} }
func (m *QueryRoomListReq) String() string { return proto.CompactTextString(m) }
func (*QueryRoomListReq) ProtoMessage()    {}
func (*QueryRoomListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *QueryRoomListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomListReq.Unmarshal(m, b)
}
func (m *QueryRoomListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomListReq.Marshal(b, m, deterministic)
}
func (m *QueryRoomListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomListReq.Merge(m, src)
}
func (m *QueryRoomListReq) XXX_Size() int {
	return xxx_messageInfo_QueryRoomListReq.Size(m)
}
func (m *QueryRoomListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomListReq.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomListReq proto.InternalMessageInfo

func (m *QueryRoomListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *QueryRoomListReq) GetPageCount() int32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type QueryRoomListResp struct {
	Code                 int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	RoomList             []*RoomInfoDTO `protobuf:"bytes,2,rep,name=RoomList,proto3" json:"RoomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryRoomListResp) Reset()         { *m = QueryRoomListResp{} }
func (m *QueryRoomListResp) String() string { return proto.CompactTextString(m) }
func (*QueryRoomListResp) ProtoMessage()    {}
func (*QueryRoomListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *QueryRoomListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRoomListResp.Unmarshal(m, b)
}
func (m *QueryRoomListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRoomListResp.Marshal(b, m, deterministic)
}
func (m *QueryRoomListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRoomListResp.Merge(m, src)
}
func (m *QueryRoomListResp) XXX_Size() int {
	return xxx_messageInfo_QueryRoomListResp.Size(m)
}
func (m *QueryRoomListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRoomListResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRoomListResp proto.InternalMessageInfo

func (m *QueryRoomListResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *QueryRoomListResp) GetRoomList() []*RoomInfoDTO {
	if m != nil {
		return m.RoomList
	}
	return nil
}

type GetInReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInReq) Reset()         { *m = GetInReq{} }
func (m *GetInReq) String() string { return proto.CompactTextString(m) }
func (*GetInReq) ProtoMessage()    {}
func (*GetInReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *GetInReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInReq.Unmarshal(m, b)
}
func (m *GetInReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInReq.Marshal(b, m, deterministic)
}
func (m *GetInReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInReq.Merge(m, src)
}
func (m *GetInReq) XXX_Size() int {
	return xxx_messageInfo_GetInReq.Size(m)
}
func (m *GetInReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInReq proto.InternalMessageInfo

func (m *GetInReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetInResp struct {
	Code                 int32        `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Room                 *RoomInfoDTO `protobuf:"bytes,2,opt,name=Room,proto3" json:"Room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetInResp) Reset()         { *m = GetInResp{} }
func (m *GetInResp) String() string { return proto.CompactTextString(m) }
func (*GetInResp) ProtoMessage()    {}
func (*GetInResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *GetInResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInResp.Unmarshal(m, b)
}
func (m *GetInResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInResp.Marshal(b, m, deterministic)
}
func (m *GetInResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInResp.Merge(m, src)
}
func (m *GetInResp) XXX_Size() int {
	return xxx_messageInfo_GetInResp.Size(m)
}
func (m *GetInResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInResp proto.InternalMessageInfo

func (m *GetInResp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetInResp) GetRoom() *RoomInfoDTO {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRoomListReq)(nil), "prt.QueryRoomListReq")
	proto.RegisterType((*QueryRoomListResp)(nil), "prt.QueryRoomListResp")
	proto.RegisterType((*GetInReq)(nil), "prt.GetInReq")
	proto.RegisterType((*GetInResp)(nil), "prt.GetInResp")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xca, 0xcf, 0xcf,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x28, 0x2a, 0x91, 0xe2, 0x4c, 0x29, 0xc9,
	0x87, 0xf0, 0x95, 0x5c, 0xb8, 0x04, 0x02, 0x4b, 0x53, 0x8b, 0x2a, 0x83, 0xf2, 0xf3, 0x73, 0x7d,
	0x32, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0x02, 0x12, 0xd3, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x19, 0x2e, 0x4e, 0x10, 0xed, 0x9c, 0x5f, 0x9a,
	0x57, 0x22, 0xc1, 0x04, 0x96, 0x40, 0x08, 0x28, 0x85, 0x72, 0x09, 0xa2, 0x99, 0x52, 0x5c, 0x00,
	0x32, 0xc6, 0x39, 0x3f, 0x05, 0x6e, 0x0c, 0x88, 0x2d, 0xa4, 0xc3, 0xc5, 0x01, 0x53, 0x23, 0xc1,
	0xa4, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0xa0, 0x57, 0x50, 0x54, 0xa2, 0x07, 0x12, 0xf4, 0xcc, 0x4b,
	0xcb, 0x77, 0x09, 0xf1, 0x0f, 0x82, 0xab, 0x50, 0x92, 0xe2, 0xe2, 0x70, 0x4f, 0x2d, 0xf1, 0xcc,
	0x03, 0x39, 0x8a, 0x8f, 0x8b, 0xc9, 0xd3, 0x05, 0x6a, 0x16, 0x93, 0xa7, 0x8b, 0x92, 0x2b, 0x17,
	0x27, 0x54, 0x0e, 0x87, 0x55, 0x2a, 0x5c, 0x2c, 0x20, 0x83, 0xc0, 0x8e, 0xc5, 0x66, 0x0d, 0x58,
	0x36, 0x89, 0x0d, 0x1c, 0x0c, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x04, 0x37, 0x83, 0x46,
	0x24, 0x01, 0x00, 0x00,
}
